on: 
  push:
    branches:
      - master

jobs:
  release-on-push:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v1

    - name: Use Node.js v12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Publish
      id: publish
      if: github.ref == 'refs/heads/master'
      uses: mikeal/merge-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    