on: push

name: Build and Publish

jobs:
  all:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish
        if: github.ref == 'refs/heads/master'
        uses: adrw/merge-release@20191119.pkgDir
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          PACKAGE_PATH: ./dist